### ISSUE TITLE
Feature request: English blueprints

### ISSUE THREAD

**Issue by texnixe** [louis-ev/Papeterie#3]

**Comment by mciszczon** [comment]
You can download my fork over here: [mciszczon/Papeterie](https://github.com/mciszczon/Papeterie). I translated the blueprints and didn't make any other changes.

**Comment by louis-ev** [comment]
Thanks! Been out of the loop lately, feel free to send a pull request with those changes.

**Comment by louis-ev** [comment]
#4 
Thanks for the PR!
