### ISSUE TITLE
syntax error, unexpected '?>'

### ISSUE THREAD

**Issue by theopaolo** [louis-ev/Papeterie#5]
Hi Louis, 
Thanks for sharing this very interesting plugin, id like to use it for a résumé/portfolio generator.
Unfortunately i get the following errors when i'm trying to preview the page document 

syntax error, unexpected '?>'

and in the debug i get this line : 

    @media screen {
      .is--overflowing::after {
        content: '<?php echo(array_key_exists($site->language(), $overflow) ? $overflow[$site->language()] : $overflow['en'] ?>';
      }
    }

Thx in advance for any help.

TheoG.

**Comment by louis-ev** [comment]
Hi Theo,
thanks for the feedback ! Glad you find this plugin interesting.
It seems the closing parenthese is missing. I am correcting it right away, can you download and test again?
Cheers,
Louis
